services:
  flaresolverr:
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Paris
    ports:
      - "8191:8191"
    restart: unless-stopped

  prowlarr:
    image: "lscr.io/linuxserver/prowlarr:latest"
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "prowlarr-config:/config"
    ports:
      - "9696:9696"
    restart: unless-stopped

  qbittorrent:
    image: "lscr.io/linuxserver/qbittorrent:latest"
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8112
      - TORRENTING_PORT=6881
    volumes:
      - "qbittorrent-config:/config"
      - "/Volumes/servarr:/downloads"
    ports:
      - "8112:8112"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  radarr:
    image: "lscr.io/linuxserver/radarr:latest"
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "radarr-config:/config"
      - "/Volumes/servarr:/data"
      - "/Volumes/servarr:/downloads"
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: "lscr.io/linuxserver/sonarr:latest"
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "sonarr-config:/config"
      - "/Volumes/servarr:/data"
      - "/Volumes/servarr:/downloads"
    ports:
      - "8989:8989"
    restart: unless-stopped

volumes:
  radarr-config: null
  sonarr-config: null
  qbittorrent-config: null
  prowlarr-config: null
